version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: financy_postgres
    environment:
      POSTGRES_DB: financy_dev
      POSTGRES_USER: financy_user
      POSTGRES_PASSWORD: financy_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - financy_network

  redis:
    image: redis:7-alpine
    container_name: financy_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - financy_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financy_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=financy_dev
      - DATABASE_USER=financy_user
      - DATABASE_PASSWORD=financy_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=development_jwt_secret_change_in_production
      - JWT_EXPIRES_IN=7d
    depends_on:
      - postgres
      - redis
    networks:
      - financy_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financy_frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - financy_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  financy_network:
    driver: bridge