import { TelegramUpdate, TelegramMessage } from '../interfaces/telegram.interface';

/**
 * Telegram messages carry users' personal financial information: what they
 * bought, where, and for how much. None of that belongs in production logs,
 * which are retained by the hosting platform and readable by anyone with
 * dashboard access.
 *
 * These helpers render payloads in full only outside production — where the
 * data is the developer's own test input — and elsewhere log the shape of the
 * payload, which is what the surrounding diagnostics actually need.
 */
const contentLoggingEnabled = (): boolean => process.env.NODE_ENV !== 'production';

/** Lists the kinds of content a message carries, without any of the content. */
const describeMessageKinds = (message?: TelegramMessage): string[] => {
  if (!message) return [];

  const kinds: string[] = [];
  if (message.text) kinds.push('text');
  if (message.caption) kinds.push('caption');
  if (message.voice) kinds.push('voice');
  if (message.audio) kinds.push('audio');
  if (message.photo) kinds.push(`photo:${message.photo.length}`);
  if (message.document) kinds.push('document');
  if (message.video) kinds.push('video');
  if (message.contact) kinds.push('contact');
  if (message.location) kinds.push('location');
  if (message.new_chat_members) kinds.push('new_chat_members');
  if (message.left_chat_member) kinds.push('left_chat_member');

  return kinds;
};

/**
 * Safe metadata for a webhook update: enough to trace which chat and which
 * kind of message a log line refers to, with no message content.
 */
export const describeUpdate = (update: TelegramUpdate): string => {
  if (contentLoggingEnabled()) {
    return JSON.stringify(update, null, 2);
  }

  const message =
    update?.message ?? update?.edited_message ?? update?.channel_post ?? update?.edited_channel_post;
  const callback = update?.callback_query;

  return JSON.stringify({
    updateId: update?.update_id,
    chatId: message?.chat?.id ?? callback?.message?.chat?.id,
    chatType: message?.chat?.type ?? callback?.message?.chat?.type,
    fromId: message?.from?.id ?? callback?.from?.id,
    kinds: describeMessageKinds(message),
    // Callback data is generated by this bot (e.g. "confirm_<id>"), not typed
    // by the user, so it is safe to keep and useful for tracing button flows.
    callbackData: callback?.data,
  });
};

/**
 * Free-form content — message text, voice transcripts, raw model output.
 * Outside production the value itself; in production only its size.
 */
export const describeContent = (content?: string): string => {
  if (contentLoggingEnabled()) {
    return content ?? '';
  }

  if (content == null) return '[empty]';
  return `[redacted, ${content.length} chars]`;
};

/**
 * A parsed transaction: the fields that were populated and how it was
 * classified, without the amounts, descriptions, or merchant names that make
 * up the user's actual financial record.
 */
export const describeTransaction = (transaction: any): string => {
  if (contentLoggingEnabled()) {
    return JSON.stringify(transaction);
  }

  if (!transaction || typeof transaction !== 'object') {
    return '[no transaction]';
  }

  return JSON.stringify({
    type: transaction.type,
    category: transaction.category,
    currency: transaction.currency,
    hasAmount: transaction.amount !== undefined && transaction.amount !== null,
    hasDescription: !!transaction.description,
    hasMerchant: !!transaction.merchantName,
    confidence: transaction.confidence,
  });
};
